/**
 * Printable exports of a loop's deliverables — pure (client-safe).
 *
 * Two formats: structured Markdown and a standalone printable HTML document.
 * Answer keys are SEPARABLE: with `includeAnswerKeys: false` only the statements
 * are emitted; with `true` the answer keys are gathered into a clearly delimited
 * trailing "Answer keys" section so a teacher can print one or both.
 */
import type { Evaluation, LoopResult, RevisionSheet, TeacherDiagnosis } from "@/classroom/domain";

export interface ExportOptions {
  includeAnswerKeys: boolean;
}

const LEVEL_LABEL: Record<Evaluation["level"], string> = {
  beginner: "Beginner",
  intermediate: "Intermediate",
  advanced: "Advanced",
};

/* ------------------------------- Markdown --------------------------------- */

function evaluationMd(ev: Evaluation, withAnswers: boolean): string {
  const lines = [`### Level ${LEVEL_LABEL[ev.level]}`, ""];
  ev.items.forEach((it, i) => {
    lines.push(`**${i + 1}. (${it.type}) ${it.statement}** _— ${it.target_concept}_`);
    if (it.options?.length) it.options.forEach((o) => lines.push(`   - ${o}`));
    if (withAnswers) lines.push(`   - _Answer key:_ ${it.answer_key}`);
    lines.push("");
  });
  return lines.join("\n");
}

function diagnosisMd(d: TeacherDiagnosis): string {
  const lines = ["## Diagnosis (summary)", ""];
  lines.push("**Misunderstood concepts:**");
  d.misunderstood_concepts.forEach((c) =>
    lines.push(`- ${c.concept} — severity ${c.severity}, ${c.frequency} student(s) [${c.affected_levels.join(", ")}]`),
  );
  lines.push("", "**Missing prerequisites:**");
  d.missing_prerequisites.forEach((p) => lines.push(`- ${p.prerequisite} — ${p.evidence}`));
  lines.push("", "**What works:**");
  d.what_works.forEach((s) => lines.push(`- ${s}`));
  lines.push("", "**Rewrite priorities:**");
  d.rewrite_priorities.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  return lines.join("\n");
}

function sheetMd(f: RevisionSheet): string {
  const lines = [`## ${f.title}`, "", "### Prerequisites", ...f.prerequisites.map((p) => `- ${p}`), ""];
  lines.push("### Key points", ...f.key_points.map((p) => `- ${p}`), "");
  lines.push("### Definitions", ...f.definitions.map((d) => `- **${d.term}**: ${d.def}`), "");
  lines.push("### Common pitfalls", ...f.common_pitfalls.map((p) => `- ${p}`));
  return lines.join("\n");
}

/* --- reusable section bodies (shared by the dossier and per-section exports) --- */

function evaluationsBody(result: LoopResult, withAnswers: boolean): string[] {
  const out = ["## Evaluations", ""];
  (["beginner", "intermediate", "advanced"] as const).forEach((lvl) => {
    out.push(evaluationMd(result.production.evaluations[lvl], withAnswers));
  });
  return out;
}

function exercisesBody(result: LoopResult, withAnswers: boolean): string[] {
  const out = ["## Exercises", ""];
  result.production.exercises.exercises.forEach((ex, i) => {
    out.push(`### ${i + 1}. ${ex.title} _(${ex.format}, ${ex.indicative_level})_`);
    out.push(ex.statement, "");
    if (withAnswers) out.push(`_Answer key:_ ${ex.answer_key}`, "");
  });
  return out;
}

/* ------------ per-section markdown builders (fed to markdownToPdf) ------------ */

/** The rewritten lesson, titled — as its own markdown document. */
export function buildLessonMarkdown(result: LoopResult): string {
  return `# ${result.lessonVersion.title}\n\n${result.lessonVersion.markdown}`;
}

/** The evaluations, as their own markdown document. */
export function buildEvaluationsMarkdown(result: LoopResult, opts: ExportOptions): string {
  return [`# ${result.lessonVersion.title} — Evaluations`, "", ...evaluationsBody(result, opts.includeAnswerKeys)].join("\n");
}

/** The exercises, as their own markdown document. */
export function buildExercisesMarkdown(result: LoopResult, opts: ExportOptions): string {
  return [`# ${result.lessonVersion.title} — Exercises`, "", ...exercisesBody(result, opts.includeAnswerKeys)].join("\n");
}

/** The revision sheet, as its own markdown document. */
export function buildSheetMarkdown(result: LoopResult): string {
  return `# ${result.lessonVersion.title} — Revision sheet\n\n${sheetMd(result.production.sheet)}`;
}

export function buildMarkdown(result: LoopResult, opts: ExportOptions): string {
  const { lessonVersion, diagnosis, production } = result;
  const out: string[] = [];
  out.push(`# ${lessonVersion.title} — Pedagogical dossier`, "");
  out.push("> Materials generated by ClassroomSim, driven by the diagnosis of the simulated classes.", "");

  out.push("## Lesson (rewritten version)", "", lessonVersion.markdown, "");
  out.push(diagnosisMd(diagnosis), "");

  out.push(...evaluationsBody(result, opts.includeAnswerKeys));
  out.push(...exercisesBody(result, opts.includeAnswerKeys));

  out.push(sheetMd(production.sheet), "");

  if (opts.includeAnswerKeys) {
    out.push("---", "", "## Answer keys (recap)", "");
    (["beginner", "intermediate", "advanced"] as const).forEach((lvl) => {
      out.push(`### Evaluation — ${LEVEL_LABEL[lvl]}`);
      production.evaluations[lvl].items.forEach((it, i) => out.push(`${i + 1}. ${it.answer_key}`));
      out.push("");
    });
    out.push("### Exercises");
    production.exercises.exercises.forEach((ex, i) => out.push(`${i + 1}. ${ex.title}: ${ex.answer_key}`));
  }

  return out.join("\n");
}

/* --------------------------------- HTML ----------------------------------- */

function esc(s: string): string {
  return s.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] ?? c);
}

function mdParasToHtml(md: string): string {
  return md
    .split(/\n{2,}/)
    .map((block) => {
      const t = block.trim();
      if (!t) return "";
      const h = t.match(/^(#{1,4})\s+(.+)$/);
      if (h) return `<h${h[1].length}>${esc(h[2])}</h${h[1].length}>`;
      return `<p>${esc(t).replace(/\n/g, "<br/>")}</p>`;
    })
    .join("\n");
}

export function buildPrintableHtml(result: LoopResult, opts: ExportOptions): string {
  const body = mdParasToHtml(buildMarkdown(result, opts));
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${esc(result.lessonVersion.title)} — Pedagogical dossier</title>
<style>
  :root { color-scheme: light; }
  body { font: 15px/1.6 -apple-system, Segoe UI, Roboto, sans-serif; max-width: 820px; margin: 2rem auto; padding: 0 1.25rem; color: #1a1a1a; }
  h1 { border-bottom: 3px solid #6d28d9; padding-bottom: .3rem; }
  h2 { margin-top: 2.2rem; color: #5b21b6; border-bottom: 1px solid #ddd; padding-bottom: .2rem; }
  h3 { margin-top: 1.4rem; color: #6d28d9; }
  blockquote { color: #555; border-left: 3px solid #c4b5fd; margin: 0; padding: .2rem 1rem; background: #faf5ff; }
  p { margin: .5rem 0; }
  @media print { body { margin: 0; max-width: none; } h2 { page-break-after: avoid; } }
</style>
</head>
<body>
${body}
</body>
</html>`;
}

/** Suggested download filename stem (no extension). */
export function exportFilename(result: LoopResult): string {
  return (
    result.lessonVersion.title
      .toLowerCase()
      .normalize("NFD")
      .replace(/\p{Diacritic}/gu, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      .slice(0, 60) || "pedagogical-dossier"
  );
}
