"""Register / connect the ClassroomSim agent to Agentverse.

============================================================================
RECOMMENDED PATH: you usually do NOT need this script.
----------------------------------------------------------------------------
The simplest and recommended way to make the agent discoverable by ASI:One
is to just run `bridge.py`. Because it is created with:

    Agent(..., mailbox=True, publish_agent_details=True)

the agent connects to the Agentverse mailbox on startup and publishes its
manifest/details automatically. When you first run it, the logs print a
mailbox connection link; open it (logged in to https://agentverse.ai) to
attach the agent to your Agentverse account. After that, ASI:One can reach it
through the Chat Protocol with no extra API calls.

============================================================================
THIS SCRIPT: the explicit-API alternative.
----------------------------------------------------------------------------
If you instead want to register/update the agent's public profile (name,
README, keywords) programmatically using an Agentverse API key, this script
shows the shape of that call. It derives the agent's identity from AGENT_SEED
(so the address matches the one bridge.py uses) and POSTs a profile update to
the Agentverse REST API.

NOTE ON THE ENDPOINT: Agentverse's REST surface evolves. The exact path used
below (`/v1/agents`) may need adjusting to the current Agentverse API — treat
it as a documented template rather than a guaranteed endpoint. The identity
derivation and auth header pattern are the stable parts; the request body /
URL should be reconciled with the latest Agentverse API docs if it 404s.
============================================================================
"""

import os
import httpx

from uagents_core.identity import Identity

AGENTVERSE_BASE = "https://agentverse.ai"


def main():
    api_key = os.getenv("AGENTVERSE_API_KEY")
    seed = os.getenv("AGENT_SEED")
    name = os.getenv("AGENT_NAME", "koro-classroomsim")

    if not api_key:
        raise RuntimeError(
            "AGENTVERSE_API_KEY is required. Create one at https://agentverse.ai "
            "(Profile > API Keys)."
        )
    if not seed:
        raise RuntimeError(
            "AGENT_SEED is required and must match the seed used by bridge.py "
            "so the registered address is the same one the agent runs under."
        )

    # Derive the deterministic identity (address) from the seed. This is the
    # same identity bridge.py uses, so we register the correct address.
    identity = Identity.from_seed(seed, 0)
    address = identity.address
    print(f"Agent address derived from seed: {address}")

    readme = (
        "# ClassroomSim (Koro) bridge\n\n"
        "Send a lesson written in **Markdown** and receive a full pedagogical "
        "dossier generated by the ClassroomSim / Mastra backend. Talk to it "
        "over the standard Chat Protocol via ASI:One or Agentverse."
    )
    keywords = ["education", "pedagogy", "classroom", "teaching", "mastra", "koro"]

    # Documented template request to the Agentverse agent-profile endpoint.
    # Reconcile URL/body with current Agentverse API docs if this 404s.
    url = f"{AGENTVERSE_BASE}/v1/agents"
    headers = {"Authorization": f"Bearer {api_key}"}
    payload = {
        "address": address,
        "name": name,
        "readme": readme,
        "keywords": keywords,
    }

    with httpx.Client(timeout=60) as client:
        resp = client.post(url, headers=headers, json=payload)
        print(f"POST {url} -> {resp.status_code}")
        print(resp.text)
        resp.raise_for_status()

    print("Registration request sent. Verify the agent at https://agentverse.ai.")


if __name__ == "__main__":
    main()
